### ISSUE TITLE
Nil value fields on launch

### ISSUE THREAD

**Issue by nedludd** [knl/mjolnir.winter#1]
Hey, I'm getting the following when I attempt to use winter.  Can you see what's going on?

I'm using just the basic default `mjolnir` config, and the example config from your page.

```
-- Loading ~/.mjolnir/init.lua
/Users/therma000/.mjolnir/init.lua:15: attempt to call field 'focused' (a nil value)
stack traceback:
    /Users/therma000/.mjolnir/init.lua:15: in main chunk
    [C]: in function 'xpcall'
    ...m/mjolnir/0.4.3/Mjolnir.app/Contents/Resources/setup.lua:73: in main chunk
```

**Comment by knl** [comment]
Hi Ned, configuration in the `README.md` file was not correct. I updated it, could you please try it out? Thanks for reporting the issue!

**Comment by nedludd** [comment]
Brilliant!  Works.  Thanks a lot!

**Comment by knl** [comment]
Glad it works for you. Please let me know if you find any more problems.
